### ISSUE TITLE
Develop branch submodule checkout fails

### ISSUE THREAD

**Issue by Gerard42** [CERT-Polska/hsn2-bundle#3]
Hi, 

Since the latest commit (d8b8971915) from yesterday I cannot checkout the develop branch for hsn2-bundle anymore (specifically the webclient module, the submodule version referenced is not uploaded to github?):

git clone -b develop --recursive https://github.com/CERT-Polska/hsn2-bundle

Unable to checkout 'e659e7c27b03e388bda6285dcdf79d0783c4b5a0' in submodule path 'hsn2-webclient'

**Comment by pawel-ch** [comment]
Hi, after b9621a58df51b15138975e6bc89b2ee2fd46ebe2 cloning in provided way should work again.

**Comment by Gerard42** [comment]
Works again, thanks!
