### ISSUE TITLE
Maven build process fails

### ISSUE THREAD

**Issue by Gerard42** [CERT-Polska/hsn2-bundle#4]
I don't know whether the following is something that you will consider fixing for now because it probably requires updating some code. It does make it difficult to compile the Github code though… Maybe you have a work-around?

The maven build process fails on at least 2 libraries (org.apache.commons:commons-ognl:jar:4.0-SNAPSHOT and org.activiti:activiti-engine:jar:5.5). The ognl error is fixable easily by obtaining ognl via subversion; which has no problem compiling. 

The Activity 5.5 package however is where I gave up building. 5.5 is not in the Maven repo’s (only newer versions). When getting 5.5 manually it also has a Maven build process. This process fails however (also because of packages not available in the Maven repos anymore). Fixing Maven dependency errors in a dependency because of old libraries not available anymore in the Maven repo’s becomes a little bit crazy, so I gave up at that point.

I also tried a newer version of Activity, but then I got compile errors in HSN2 due to this newer version.

The errors are below:

Missing:
----------
1) org.apache.commons:commons-ognl:jar:4.0-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command:
      mvn install:install-file -DgroupId=org.apache.commons -DartifactId=commons-ognl -Dversion=4.0-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there:
      mvn deploy:deploy-file -DgroupId=org.apache.commons -DartifactId=commons-ognl -Dversion=4.0-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency:
        1) pl.nask.hsn2:hsn2-configuration:jar:1.0.0-SNAPSHOT
        2) org.apache.commons:commons-ognl:jar:4.0-SNAPSHOT

----------
1 required artifact is missing.

for artifact:
  pl.nask.hsn2:hsn2-configuration:jar:1.0.0-SNAPSHOT

from the specified remote repositories:
  central (http://repo1.maven.org/maven2)

Missing:
----------
1) org.activiti:activiti-engine:jar:5.5

  Try downloading the file manually from the project website.

  Then, install it using the command:
      mvn install:install-file -DgroupId=org.activiti -DartifactId=activiti-engine -Dversion=5.5 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there:
      mvn deploy:deploy-file -DgroupId=org.activiti -DartifactId=activiti-engine -Dversion=5.5 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency:
        1) pl.nask.hsn2:hsn2-workflow-engine:jar:1.0.0-SNAPSHOT
        2) org.activiti:activiti-engine:jar:5.5

----------
1 required artifact is missing.

for artifact:
  pl.nask.hsn2:hsn2-workflow-engine:jar:1.0.0-SNAPSHOT

from the specified remote repositories:
  central (http://repo1.maven.org/maven2)

**Comment by pawel-ch** [comment]
Hi Gerard,

You could try the following before building:
<pre>
wget https://maven.alfresco.com/nexus/content/repositories/activiti-releases/org/activiti/activiti-engine/5.5/activiti-engine-5.5.jar
wget https://maven.alfresco.com/nexus/content/repositories/activiti-releases/org/activiti/activiti-engine/5.5/activiti-engine-5.5.pom
mkdir -p ~/.m2/repository/org/activiti/activiti-engine/5.5
cp activiti-engine-5.5.* ~/.m2/repository/org/activiti/activiti-engine/5.5/
</pre>

**Comment by Gerard42** [comment]
Thanks, that helped. 

I now get a build failure on test failures:

Failed tests:   checkTestWebsiteByWebclient(pl.nask.hsn2.service.AllSitesTest): Task is not sucessful for page: http://localhost:8123/jsTests/index.html expected [true] but found [false]

Do I need to set-up a test webserver or should this be included in the build process?

**Comment by Gerard42** [comment]
Tried again with the 2.1 release; everything compiles now. For the tests I had to install libfuzzy2 though, which probably should be added to the list of dependencies in the README from hsn2-bundle.
